
DO 
$do$
BEGIN
--CORROBACIÓN DE QUE LA TABLA MONEDA EXISTE
IF NOT EXISTS (SELECT table_name FROM information_schema.columns WHERE table_name='moneda') THEN 
	CREATE TABLE Moneda( 
	Id SERIAL PRIMARY KEY,
	Nombre VARCHAR(30) NOT NULL, 
	Sigla VARCHAR(10) NULL,
	Imagen Bytea NULL);
	CREATE UNIQUE INDEX  ixMoneda_Nombre
   ON moneda (Id);
	
ELSE 
--SALIDA EN CASO QUE EXISTA LA TABLA, AVISO
	RAISE INFO 'LA TABLA MONEDA YA EXISTE';
	
END IF;

--CORROBACIÓN DE QUE EXISTE LA COLUMNA MONEDA EN PAIS, SALIDA
IF NOT EXISTS( SELECT column_name FROM information_schema.columns WHERE column_name='moneda')  THEN
	RAISE INFO 'NO SE PUEDE REALIZAR LA OPERACIÓN';
	
--REALIZAR OPERACIÓN PARA PRIMERA VEZ
ELSE 
	INSERT INTO Moneda(Nombre) 
		SELECT DISTINCT Moneda
			FROM Pais;

	ALTER TABLE Pais
		ADD COLUMN IF NOT EXISTS IdMoneda INTEGER;

	UPDATE Pais
		SET IdMoneda = M.Id
		FROM Moneda M
		WHERE Pais.Moneda = M.Nombre;

	ALTER TABLE Pais
		ADD CONSTRAINT fkPais_idMoneda FOREIGN KEY (IdMoneda) REFERENCES Moneda(Id);

	ALTER TABLE Pais 
		DROP COLUMN Moneda;
	
	--AGREGAR COLUMNAS MAPA Y BANDERA QUE SOPORTEN IMAGEN
	ALTER TABLE Pais
		ADD COLUMN Bandera Bytea NULL;
		
	ALTER TABLE Pais
		ADD COLUMN MAPA Bytea NULL;
	
END IF;	


END;

$do$;



	
